CREATE TABLE mmrc_bacterial_pathway_sam AS 
  sample_id string,
  source_file string,
  batch_year string,
  batch_month string,
  batch_day string,
  pectin degradation i double,
  l-tyrosine degradation v (stickland reaction) double,
  cmp-legionaminate biosynthesis i double,
  beta-carotene biosynthesis double,
  nitrite-dependent anaerobic methane oxidation double,
  4-hydroxyphenylacetate degradation double,
  bis(guanylyl molybdenum cofactor) biosynthesis double,
  pyrimidine deoxyribonucleosides degradation double,
  phenylethylamine degradation ii double,
  5-oxo-l-proline metabolism double,
  l-isoleucine degradation i double,
  nad phosphorylation and transhydrogenation double,
  formaldehyde assimilation i (serine pathway) double,
  pederin biosynthesis double,
  pectin degradation ii double,
  sucrose degradation iv (sucrose phosphorylase) double,
  2-carboxy-1,4-naphthoquinol biosynthesis double,
  ubiquinol-8 biosynthesis (early decarboxylation) double,
  fatty acid biosynthesis initiation (type ii) double,
  femo cofactor biosynthesis double,
  gdp-l-fucose biosynthesis i (from gdp-d-mannose) double,
  5-hexynoate biosynthesis double,
  3,5-dichlorocatechol degradation double,
  arsenate detoxification ii (glutaredoxin) double,
  demethylmenaquinol-9 biosynthesis double,
  nylon-6 oligomer degradation double,
  ribose phosphorylation double,
  glyoxylate cycle double,
  l-homocysteine biosynthesis double,
  cinnamate and 3-hydroxycinnamate degradation to 2-hydroxypentadienoate double,
  l-methionine degradation i (to l-homocysteine) double,
  glycerophosphodiester degradation double,
  manganese oxidation ii double,
  cmp-legionaminate biosynthesis ii double,
  aminopropanol phosphate biosynthesis i double,
  udp-alpha-d-glucose biosynthesis i double,
  4-coumarate degradation (aerobic) double,
  phosphatidylcholine biosynthesis vi double,
  dipicolinate biosynthesis double,
  nadh to cytochrome bd oxidase electron transfer i double,
  glucosylglycerol biosynthesis double,
  citrate degradation double,
  geranylgeranyl diphosphate biosynthesis double,
  pyochelin biosynthesis double,
  cmp-pseudaminate biosynthesis double,
  d-sorbitol degradation i double,
  d-galacturonate degradation i double,
  l-aspartate degradation ii (aerobic) double,
  hypotaurine degradation double,
  1,4-dihydroxy-6-naphthoate biosynthesis ii double,
  assimilatory sulfate reduction iii double,
  cyanate degradation double,
  cmp-n-acetylneuraminate biosynthesis ii (bacteria) double,
  tca cycle vi (helicobacter) double,
  glycerol degradation ii double,
  (s)-propane-1,2-diol degradation double,
  sulfur reduction i double,
  cholesterol degradation to androstenedione i (cholesterol oxidase) double,
  pyrimidine ribonucleosides salvage ii double,
  l-leucine degradation iv (stickland reaction) double,
  udp-alpha-d-glucuronate biosynthesis (from udp-glucose) double,
  l-isoleucine degradation iii (oxidative stickland reaction) double,
  ectoine degradation double,
  l-tyrosine degradation i double,
  mycocyclosin biosynthesis double,
  cell-surface glycoconjugate-linked phosphocholine biosynthesis double,
  4-aminobenzoate biosynthesis i double,
  l-asparagine biosynthesis i double,
  l-leucine degradation v (oxidative stickland reaction) double,
  4-hydroxyphenylpyruvate biosynthesis double,
  bacteriochlorophyll b biosynthesis double,
  l-glutamate biosynthesis iii double,
  thiosulfate disproportionation iv (rhodanese) double,
  l-histidine degradation ii double,
  mannosylglycerate biosynthesis ii double,
  creatinine degradation i double,
  l-serine degradation double,
  udp-alpha-d-galacturonate biosynthesis i (from udp-d-glucuronate) double,
  l-arginine degradation ii (ast pathway) double,
  2-methyladeninyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  udp-<i>n,n'</i>-diacetylbacillosamine biosynthesis double,
  pentachlorophenol degradation double,
  glutathione biosynthesis double,
  l-methionine biosynthesis ii (plants) double,
  cephamycin c biosynthesis double,
  heme b biosynthesis v (aerobic) double,
  l-rhamnose degradation i double,
  pyridoxal 5'-phosphate salvage ii (plants) double,
  itaconate degradation double,
  vanillin and vanillate degradation i double,
  chorismate biosynthesis from 3-dehydroquinate double,
  calvin-benson-bassham cycle double,
  homospermidine biosynthesis i double,
  sulfur reduction ii (via polysulfide) double,
  glycogen biosynthesis i (from adp-d-glucose) double,
  trans-lycopene biosynthesis ii (oxygenic phototrophs and green sulfur bacteria) double,
  isopenicillin n biosynthesis double,
  beta-alanine biosynthesis ii double,
  biotin-carboxyl carrier protein assembly double,
  pyruvate fermentation to (s)-acetoin double,
  lipid iva biosynthesis (p. gingivalis) double,
  sucrose degradation ii (sucrose synthase) double,
  d-gluconate degradation double,
  chlorosalicylate degradation double,
  gdp-d-perosamine biosynthesis double,
  aerobactin biosynthesis double,
  malonate degradation ii (biotin-dependent) double,
  cardiolipin biosynthesis iii double,
  5-methoxybenzimidazolyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  l-lyxonate degradation double,
  4-sulfocatechol degradation double,
  hyaluronan degradation double,
  adenosylcobalamin salvage from cobalamin double,
  d-malate degradation double,
  benzoyl-coa degradation ii (anaerobic) double,
  tetrahydrofolate biosynthesis ii double,
  oxalate degradation v double,
  pyruvate to cytochrome bd oxidase electron transfer double,
  l-leucine degradation i double,
  fluoroacetate and fluorothreonine biosynthesis double,
  l-threonate degradation double,
  even iso-branched-chain fatty acid biosynthesis double,
  citrate lyase activation double,
  dimethyl sulfide degradation iii (oxidation) double,
  6-hydroxymethyl-dihydropterin diphosphate biosynthesis i double,
  l-asparagine degradation i double,
  thiamine diphosphate salvage iv (yeast) double,
  3-phenylpropanoate and 3-(3-hydroxyphenyl)propanoate degradation to 2-hydroxypentadienoate double,
  catechol degradation to beta-ketoadipate double,
  l-citrulline biosynthesis double,
  fatty acid biosynthesis initiation (mitochondria) double,
  ppgpp metabolism double,
  cis-vaccenate biosynthesis double,
  nad salvage pathway ii (pnc iv cycle) double,
  ketogenesis double,
  ump biosynthesis iii double,
  ammonia oxidation i (aerobic) double,
  biphenyl degradation double,
  chlorpyrifos degradation double,
  acyl-[acyl-carrier protein] thioesterase pathway double,
  udp-n-acetyl-alpha-d-mannosaminouronate biosynthesis double,
  folate polyglutamylation double,
  arsenate detoxification v double,
  pyridoxal 5'-phosphate salvage i double,
  reductive glycine pathway double,
  triacylglycerol degradation double,
  l-alanine degradation iv double,
  nadh to fumarate electron transfer double,
  dipyrromethane cofactor biosynthesis double,
  photosynthesis light reactions double,
  l-lactaldehyde degradation (aerobic) double,
  l-tryptophan degradation ii (via pyruvate) double,
  2-aminoethylphosphonate degradation ii double,
  l-lysine biosynthesis iii double,
  hentriaconta-3,6,9,12,15,19,22,25,28-nonaene biosynthesis double,
  lactose and galactose degradation i double,
  pyridoxal 5'-phosphate biosynthesis ii double,
  melibiose degradation double,
  l-idonate degradation double,
  fucose degradation double,
  ubiquinol-8 biosynthesis (prokaryotic) double,
  adenosylcobinamide-gdp salvage from cobinamide i double,
  uracil degradation iii double,
  putrescine biosynthesis i double,
  adeninyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  phosphatidylinositol biosynthesis i (bacteria) double,
  trans-3-hydroxy-l-proline degradation double,
  oleandomycin activation/inactivation double,
  l-aspartate degradation iii (anaerobic) double,
  methylthiopropanoate degradation i (cleavage) double,
  l-arginine biosynthesis ii (acetyl cycle) double,
  l-proline degradation ii (reductive stickland reaction) double,
  5,6-dimethylbenzimidazole biosynthesis i (aerobic) double,
  deacetylcephalosporin c biosynthesis double,
  histamine biosynthesis double,
  nitrate reduction i (denitrification) double,
  molybdopterin biosynthesis double,
  succinate to cytochrome bo oxidase electron transfer double,
  l-valine degradation iii (oxidative stickland reaction) double,
  holomycin biosynthesis double,
  thiamine phosphate formation from pyrithiamine and oxythiamine (yeast) double,
  d-threonate degradation double,
  4-hydroxybenzoate biosynthesis ii (bacteria) double,
  nitrate reduction iii (dissimilatory) double,
  tetrahydromonapterin biosynthesis double,
  demethylmenaquinol-6 biosynthesis i double,
  l-phenylalanine biosynthesis ii double,
  glucosylglycerate biosynthesis i double,
  staphyloferrin b biosynthesis double,
  oleandomycin biosynthesis double,
  sulfite oxidation iii double,
  4-aminobutanoate degradation i double,
  d-mannose degradation ii double,
  pentose phosphate pathway (oxidative branch) i double,
  formaldehyde oxidation ii (glutathione-dependent) double,
  5-hydroxybenzimidazole biosynthesis (anaerobic) double,
  udp-yelosamine biosynthesis double,
  autoinducer ai-1 biosynthesis double,
  glycine betaine degradation i double,
  guanylyl molybdenum cofactor biosynthesis double,
  salicylate biosynthesis i double,
  heme b biosynthesis i (aerobic) double,
  glycolysis i (from glucose 6-phosphate) double,
  beta-d-glucuronide and d-glucuronate degradation double,
  (r)-cysteate degradation double,
  petrobactin biosynthesis double,
  l-cysteine biosynthesis iii (from l-homocysteine) double,
  dtdp-beta-l-rhamnose biosynthesis double,
  trna charging double,
  menaquinol-8 biosynthesis double,
  violacein biosynthesis double,
  5-aminoimidazole ribonucleotide biosynthesis i double,
  glutaminyl-trnagln biosynthesis via transamidation double,
  fatty acid beta-oxidation ii (plant peroxisome) double,
  menaquinol-6 biosynthesis double,
  2-methylcitrate cycle i double,
  dimethylsulfoniopropanoate degradation iii (demethylation) double,
  lipoate biosynthesis and incorporation iii (bacillus) double,
  spirilloxanthin and 2,2'-diketo-spirilloxanthin biosynthesis double,
  lipid iva biosynthesis (h. pylori) double,
  d-xylose degradation v double,
  3-chlorocatechol degradation ii (ortho) double,
  allantoin degradation to ureidoglycolate ii (ammonia producing) double,
  lipoprotein posttranslational modification double,
  4-aminobutanoate degradation ii double,
  l-cysteine biosynthesis i double,
  xanthine and xanthosine salvage double,
  aminopropanol phosphate biosynthesis ii double,
  l-cysteine degradation iii double,
  l-tryptophan biosynthesis double,
  glycerol degradation v double,
  androstenedione degradation double,
  cytidylyl molybdenum cofactor sulfurylation double,
  choline biosynthesis iii double,
  pyruvate fermentation to (r)-lactate double,
  palmitoleate biosynthesis ii (plants and bacteria) double,
  l-proline degradation i double,
  proline to cytochrome bo oxidase electron transfer double,
  anteiso-branched-chain fatty acid biosynthesis double,
  protocatechuate degradation iii (para-cleavage pathway) double,
  guanine and guanosine salvage iii double,
  fatty acid elongation -- saturated double,
  benzoyl-coa degradation i (aerobic) double,
  ethene and chloroethene degradation double,
  galactitol degradation double,
  heme b biosynthesis ii (oxygen-independent) double,
  palmitate biosynthesis iii double,
  formaldehyde oxidation vi (h4mpt pathway) double,
  thioredoxin pathway double,
  2-aminophenol degradation double,
  l-lysine degradation iv double,
  homospermidine biosynthesis double,
  5-methylbenzimidazolyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  phenylethanol degradation double,
  thiazole component of thiamine diphosphate biosynthesis i double,
  3-chlorobenzoate degradation i (via chlorocatechol) double,
  dtdp-l-rhamnose biosynthesis double,
  two-component alkanesulfonate monooxygenase double,
  l-galactonate degradation double,
  4-chloronitrobenzene degradation double,
  inosine-5'-phosphate biosynthesis ii double,
  3-chlorocatechol degradation i (ortho) double,
  l-methionine biosynthesis ii double,
  2-methylcitrate cycle ii double,
  adenine and adenosine salvage iii double,
  cyclopropane fatty acid (cfa) biosynthesis double,
  catechol degradation to 2-hydroxypentadienoate ii double,
  trehalose degradation vi (periplasmic) double,
  lipoate salvage ii double,
  astaxanthin biosynthesis (bacteria, fungi, algae) double,
  hydrogen production iii double,
  phospholipases double,
  udp-n-acetylmuramoyl-pentapeptide biosynthesis ii (lysine-containing) double,
  tca cycle ii (plants and fungi) double,
  glyphosate degradation ii double,
  l-arginine degradation i (arginase pathway) double,
  nadh to cytochrome bo oxidase electron transfer ii double,
  cis-alkene biosynthesis double,
  hydrogen oxidation i (aerobic) double,
  guanosine ribonucleotides de novo biosynthesis double,
  l-isoleucine biosynthesis ii double,
  cob(ii)yrinate a,c-diamide biosynthesis ii (late cobalt incorporation) double,
  trehalose degradation i (low osmolarity) double,
  arsenite oxidation ii (respiratory) double,
  2-deoxy-d-ribose degradation ii double,
  tetrahydrofolate biosynthesis double,
  methyl parathion degradation double,
  purine deoxyribonucleosides salvage double,
  l-aspartate degradation i double,
  utp and ctp dephosphorylation i double,
  octanoyl-[acyl-carrier protein] biosynthesis (mitochondria, yeast) double,
  d-galactonate degradation double,
  polyvinyl alcohol degradation double,
  2-isopropylphenol degradation double,
  bis(guanylyl molybdopterin) cofactor sulfurylation double,
  mannitol degradation i double,
  cob(ii)yrinate a,c-diamide biosynthesis i (early cobalt insertion) double,
  glycerol degradation i double,
  l-alanine biosynthesis i double,
  pentose phosphate pathway (non-oxidative branch) i double,
  l-isoleucine biosynthesis iv double,
  formate oxidation to co2 double,
  mixed acid fermentation double,
  cis-geranyl-coa degradation double,
  thiosulfate disproportionation ii (cytochrome) double,
  nitrate reduction vi (assimilatory) double,
  alpha-diglucosyldiacylglycerol biosynthesis double,
  adenine and adenosine salvage ii double,
  utp and ctp dephosphorylation ii double,
  pyrimidine ribonucleosides salvage iii double,
  acetate and atp formation from acetyl-coa ii double,
  rubisco shunt double,
  d-arabinose degradation i double,
  acetate and atp formation from acetyl-coa i double,
  urea degradation ii double,
  pyruvate fermentation to propanoate i double,
  mercaptosuccinate degradation double,
  glucose and glucose-1-phosphate degradation double,
  5-aminoimidazole ribonucleotide biosynthesis ii double,
  nonaprenyl diphosphate biosynthesis i double,
  vanchrobactin biosynthesis double,
  udp-alpha-d-galactose biosynthesis double,
  pyruvate to cytochrome bo oxidase electron transfer double,
  spermidine biosynthesis iii double,
  4-nitrotoluene degradation ii double,
  d-mannose degradation double,
  sphingomyelin metabolism double,
  glycine biosynthesis i double,
  2,4,6-trichlorophenol degradation double,
  n-acetylneuraminate and n-acetylmannosamine degradation i double,
  demethylmenaquinol-8 biosynthesis i double,
  selenate reduction double,
  flaviolin dimer and mompain biosynthesis double,
  coenzyme a biosynthesis i (prokaryotic) double,
  nitrobenzene degradation i double,
  d-glucosaminate degradation double,
  rhamnolipid biosynthesis double,
  4-chloro-2-methylphenoxyacetate degradation double,
  n6-l-threonylcarbamoyladenosine37-modified trna biosynthesis double,
  l-tryptophan degradation vi (via tryptamine) double,
  pyruvate fermentation to acetate ii double,
  guanosine nucleotides degradation iii double,
  lactose degradation iii double,
  8-oxo-(d)gtp detoxification ii double,
  ectoine biosynthesis double,
  heparan sulfate degradation double,
  8-amino-7-oxononanoate biosynthesis iii double,
  heme a biosynthesis double,
  adenosine deoxyribonucleotides de novo biosynthesis ii double,
  bile acid 7beta-dehydroxylation double,
  trehalose biosynthesis v double,
  salmochelin degradation double,
  molybdenum cofactor sulfulylation (eukaryotes) double,
  l-glutamine degradation ii double,
  ethanol degradation ii double,
  formate to nitrite electron transfer double,
  l-homophenylalanine biosynthesis double,
  quinate degradation i double,
  tetrahydrofolate salvage from 5,10-methenyltetrahydrofolate double,
  thiazole component of thiamine diphosphate biosynthesis ii double,
  demethylmenaquinol-8 biosynthesis ii double,
  stearate biosynthesis iii (fungi) double,
  cdp-diacylglycerol biosynthesis i double,
  2-deoxy-alpha-d-ribose 1-phosphate degradation double,
  salicylate degradation i double,
  glutaryl-coa degradation double,
  malonate degradation i (biotin-independent) double,
  l-carnitine respiration double,
  trehalose degradation ii (cytosolic) double,
  maltose degradation double,
  gdp-d-glycero-alpha-d-manno-heptose biosynthesis double,
  nadp biosynthesis double,
  dibenzothiophene desulfurization double,
  testosterone and androsterone degradation to androstendione (aerobic) double,
  nitrogen fixation i (ferredoxin) double,
  4,4'-disulfanediyldibutanoate degradation double,
  glycine degradation (stickland reaction) double,
  bifidobacterium shunt double,
  3,8-divinyl-chlorophyllide a biosynthesis ii (anaerobic) double,
  thiazole component of thiamne diphosphate biosynthesis double,
  heme b biosynthesis iii (from siroheme) double,
  putrescine degradation i double,
  nitrate reduction iv (dissimilatory) double,
  4,5-dichlorocatechol degradation double,
  nadph repair (eukaryotes) double,
  acetate conversion to acetyl-coa double,
  hydrogen oxidation iii (anaerobic, nadp) double,
  (5z)-dodecenoate biosynthesis i double,
  4-hydroxybenzoate biosynthesis iii (plants) double,
  8-oxo-(d)gtp detoxification i double,
  phosphatidylserine and phosphatidylethanolamine biosynthesis i double,
  nitrate reduction ix (dissimilatory) double,
  nitrate reduction viii (dissimilatory) double,
  cardiolipin biosynthesis i double,
  ornithine lipid biosynthesis double,
  hydrogen production vi double,
  starch degradation iii double,
  heme degradation vi double,
  cmp-diacetamido-8-epilegionaminic acid biosynthesis double,
  benzimidazolyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  chlorate reduction double,
  l-citrulline degradation double,
  glycolysis iv double,
  l-histidine degradation iii double,
  udp-2,3-diacetamido-2,3-dideoxy-alpha-d-mannuronate biosynthesis double,
  menaquinol-7 biosynthesis double,
  phenylethylamine degradation i double,
  spheroidene and spheroidenone biosynthesis double,
  s-methyl-5'-thioadenosine degradation iv double,
  l-isoleucine biosynthesis v double,
  sulfite oxidation ii double,
  3-sulfopropanediol degradation double,
  mevalonate pathway i (eukaryotes and bacteria) double,
  tca cycle i (prokaryotic) double,
  l-arginine degradation vi (arginase 2 pathway) double,
  staphyloferrin a biosynthesis double,
  trna-uridine 2-thiolation and selenation (bacteria) double,
  blasticidin s biosynthesis double,
  5-methoxy-6-methylbenzimidazolyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  l-cysteine biosynthesis v (mycobacteria) double,
  autoinducer ai-2 degradation double,
  acetoacetate degradation (to acetyl coa) double,
  thiocyanate degradation ii double,
  propene degradation double,
  carbon monoxide oxidation to co2 double,
  l-phenylalanine degradation vi (stickland reaction) double,
  arginine dependent acid resistance double,
  l-serine biosynthesis i double,
  chlorinated phenols degradation double,
  acrylate degradation ii double,
  odd iso-branched-chain fatty acid biosynthesis double,
  4-amino-2-methyl-5-diphosphomethylpyrimidine biosynthesis i double,
  1,2-dichloroethane degradation double,
  d-galactarate degradation i double,
  nad de novo biosynthesis i (from aspartate) double,
  heptadecane biosynthesis double,
  glucose degradation (oxidative) double,
  inulin degradation double,
  l-ornithine biosynthesis ii double,
  creatinine degradation ii double,
  d-arginine degradation double,
  aromatic biogenic amine degradation (bacteria) double,
  d-phenylglycine degradation double,
  methylamine degradation ii double,
  dissimilatory sulfate reduction ii (to thiosulfate) double,
  fosfomycin biosynthesis double,
  ethanolamine utilization double,
  4-coumarate degradation (anaerobic) double,
  l-glutamate degradation x double,
  chitin deacetylation double,
  2-acetamido-4-amino-2,4,6-trideoxy-alpha-d-galactosyl-diphospho-ditrans,octacis-undecaprenol biosynthesis double,
  acyl carrier protein metabolism double,
  propanoyl coa degradation i double,
  siroheme biosynthesis double,
  pyruvate decarboxylation to acetyl coa i double,
  nad salvage pathway v (pnc v cycle) double,
  glycine degradation (reductive stickland reaction) double,
  cdp-diacylglycerol biosynthesis iii double,
  assimilatory sulfate reduction iv double,
  arsenate detoxification iv (mycothiol) double,
  thiamine diphosphate biosynthesis ii (bacillus) double,
  platensimycin biosynthesis double,
  l-threonine degradation iii (to methylglyoxal) double,
  l-histidine biosynthesis double,
  octaprenyl diphosphate biosynthesis double,
  dtdp-n-acetylviosamine biosynthesis double,
  thymine degradation double,
  nicotine degradation iii (vpp pathway) double,
  propanoyl-coa degradation ii double,
  methylgallate degradation double,
  prpp biosynthesis double,
  nitrogen fixation ii (flavodoxin) double,
  tetrahydropteridine recycling double,
  d-glucarate degradation i double,
  curcumin degradation double,
  heme degradation v double,
  hydrogen production ii double,
  thiamine diphosphate biosynthesis i (e. coli) double,
  l-lactaldehyde degradation (anaerobic) double,
  3-methylthiopropanoate biosynthesis double,
  l-glutamate biosynthesis i double,
  hydroxymethylpyrimidine salvage double,
  partial tca cycle (obligate autotrophs) double,
  l-tryptophan degradation to 2-amino-3-carboxymuconate semialdehyde double,
  pyrimidine deoxyribonucleotides de novo biosynthesis i double,
  5-(methoxycarbonylmethoxy)uridine biosynthesis double,
  phosphatidylcholine biosynthesis v double,
  reductive monocarboxylic acid cycle double,
  gellan degradation double,
  heptaprenyl diphosphate biosynthesis double,
  urate conversion to allantoin ii double,
  5-methoxybenzimidazole biosynthesis (anaerobic) double,
  glycogen degradation i double,
  l-cysteine biosynthesis vii (from s-sulfo-l-cysteine) double,
  serine racemization double,
  d-erythronate degradation ii double,
  erythritol degradation ii double,
  5-chloro-3-methyl-catechol degradation double,
  l-methionine degradation ii double,
  udp-n-acetylmuramoyl-pentapeptide biosynthesis i (meso-diaminopimelate containing) double,
  d-gulosides conversion to d-glucosides double,
  alginate degradation double,
  nad biosynthesis from 2-amino-3-carboxymuconate semialdehyde double,
  glycine biosynthesis iii double,
  chlorophyll a biosynthesis ii double,
  choline degradation iii double,
  l-tyrosine biosynthesis i double,
  nad de novo biosynthesis iv (anaerobic) double,
  adenosine nucleotides degradation iii double,
  fructan biosynthesis double,
  geranyl diphosphate biosynthesis double,
  guanine and guanosine salvage ii double,
  l-glutamine biosynthesis i double,
  iota-carrageenan degradation double,
  cadaverine biosynthesis double,
  thio-molybdenum cofactor biosynthesis double,
  l-homoserine biosynthesis double,
  9-decynoate biosynthesis double,
  adenosylcobinamide-gdp biosynthesis from cobyrinate a,c-diamide double,
  dermatan sulfate degradation i (bacterial) double,
  parathion degradation double,
  l-selenocysteine biosynthesis i (bacteria) double,
  l-leucine biosynthesis double,
  uracil degradation i (reductive) double,
  paraoxon degradation double,
  myristate biosynthesis (mitochondria) double,
  l-phenylalanine biosynthesis i double,
  allantoin degradation to ureidoglycolate i (urea producing) double,
  l-isoleucine biosynthesis i (from threonine) double,
  adenosine ribonucleotides de novo biosynthesis double,
  2-aminoethylphosphonate degradation i double,
  fructose degradation double,
  l-glutamine biosynthesis iii double,
  agarose degradation double,
  glutathione-glutaredoxin redox reactions double,
  glycerol-3-phosphate to fumarate electron transfer double,
  pyrimidine ribonucleosides degradation double,
  4-oxopentanoate degradation double,
  porphyran degradation double,
  stearate biosynthesis ii (bacteria and plants) double,
  rhizobitoxine biosynthesis double,
  thiamine diphosphate biosynthesis iii (staphylococcus) double,
  l-threonine degradation iv double,
  pyruvate fermentation to ethanol i double,
  3,8-divinyl-chlorophyllide a biosynthesis iii (aerobic, light independent) double,
  phenylacetate degradation ii (anaerobic) double,
  glycogen degradation ii double,
  lipid iva biosynthesis (generic) double,
  phenylacetate degradation i (aerobic) double,
  rhamnogalacturonan type i degradation ii (bacteria) double,
  s-adenosyl-l-methionine salvage ii double,
  2-aminoethylphosphonate biosynthesis double,
  inosine-5'-phosphate biosynthesis i double,
  d-altritol and galactitol degradation double,
  pulcherrimin biosynthesis double,
  l-carnitine degradation i double,
  pyridoxal 5'-phosphate biosynthesis i double,
  trans-caffeate degradation (aerobic) double,
  ethanol degradation i double,
  peptidoglycan maturation (meso-diaminopimelate containing) double,
  tca cycle iv (2-oxoglutarate decarboxylase) double,
  5'-deoxyadenosine degradation i double,
  bile acids deconjugation double,
  adenosine deoxyribonucleotides de novo biosynthesis i double,
  3-methylarginine biosynthesis double,
  adenosine deoxyribonucleotides de novo biosynthesis double,
  staphylopine biosynthesis double,
  pyrimidine deoxyribonucleosides salvage double,
  l-threitol degradation double,
  gondoate biosynthesis (anaerobic) double,
  l-glutamate degradation i double,
  glycerol-3-phosphate to cytochrome bo oxidase electron transfer double,
  flavin salvage double,
  (s)-lactate fermentation to propanoate, acetate and hydrogen double,
  inosine 5'-phosphate degradation double,
  nadh to cytochrome bd oxidase electron transfer ii double,
  hydrogen oxidation ii (aerobic, nad) double,
  kdo transfer to lipid iva ii (haemophilus) double,
  s-methyl-5-thio-alpha-d-ribose 1-phosphate degradation i double,
  thiosulfate oxidation iii (multienzyme complex) double,
  nadh to dimethyl sulfoxide electron transfer double,
  adenosine nucleotides degradation ii double,
  glycogen biosynthesis iii (from alpha-maltose 1-phosphate) double,
  l-fucose degradation i double,
  3-(4-hydroxyphenyl)pyruvate biosynthesis double,
  nad biosynthesis iii (from nicotinamide) double,
  all-trans-decaprenyl diphosphate biosynthesis double,
  cyanophycin metabolism double,
  glycolysis iii (from glucose) double,
  (r,r)-butanediol biosynthesis double,
  stearate biosynthesis iv double,
  hydrogen production v double,
  2,4-dichlorotoluene degradation double,
  acetoin degradation double,
  isopropylamine degradation double,
  heme degradation iii double,
  l-arginine degradation iii (arginine decarboxylase/agmatinase pathway) double,
  glycolate and glyoxylate degradation ii double,
  cmp phosphorylation double,
  pyrimidine ribonucleosides salvage i double,
  protocatechuate degradation ii (ortho-cleavage pathway) double,
  (1,4)-beta-d-xylan degradation double,
  kappa-carrageenan degradation double,
  arsenite methylation (bacterial) double,
  preq0 biosynthesis double,
  mannosylglycerate biosynthesis i double,
  4-deoxy-l-threo-hex-4-enopyranuronate degradation double,
  gallate degradation i double,
  palmitate biosynthesis ii (bacteria and plant cytoplasm) double,
  utp and ctp de novo biosynthesis double,
  vancomycin resistance ii double,
  gdp-6-deoxy-d-manno-heptose biosynthesis double,
  acetone degradation ii (to acetoacetate) double,
  nadh repair (prokaryotes) double,
  erythromycin d biosynthesis double,
  adenine and adenosine salvage i double,
  3-dehydroquinate biosynthesis i double,
  l-methionine biosynthesis i double,
  bacilysin biosynthesis double,
  guanine and guanosine salvage double,
  pyruvate fermentation to ethanol iii double,
  entner-doudoroff shunt double,
  alanine racemization double,
  glycine biosynthesis iv double,
  malonate decarboxylase activation double,
  nadh to cytochrome bo oxidase electron transfer i double,
  autoinducer ai-2 biosynthesis i double,
  lipid iva biosynthesis (p. putida) double,
  l-threonine degradation ii double,
  methylsalicylate degradation double,
  sulfolactate degradation ii double,
  nad/nadp-nadh/nadph cytosolic interconversion (yeast) double,
  roxarsone degradation i double,
  limonene degradation ii (l-limonene) double,
  heme degradation vii double,
  palmitate biosynthesis (type ii fatty acid synthase) double,
  5-hydroxybenzimidazolyl adenosylcobamide biosynthesis from adenosylcobinamide-gdp double,
  tetrapyrrole biosynthesis ii (from glycine) double,
  tetramethylpyrazine degradation double,
  daidzin and daidzein degradation double,
  dimethyl sulfide biosynthesis from methionine double,
  4-aminobenzoate biosynthesis double,
  l-dopa and l-dopachrome biosynthesis double,
  s-adenosyl-l-methionine biosynthesis double,
  bile acid 7alpha-dehydroxylation double,
  guanosine deoxyribonucleotides de novo biosynthesis i double,
  l-sorbose degradation double,
  muropeptide degradation double,
  naphthalene degradation (aerobic) double,
  lipid iva biosynthesis (e. coli) double,
  3-chlorobenzoate degradation iii (via gentisate) double,
  methylphosphonate degradation i double,
  dissimilatory sulfate reduction i (to hydrogen sufide)) double,
  prenylated fmnh2 biosynthesis double,
  tca cycle v (2-oxoglutarate synthase) double,
  (kdo)2-lipid a biosynthesis i (brucella) double,
  n-acetylglutaminylglutamine amide biosynthesis double,
  pyrimidine deoxyribonucleotide phosphorylation double,
  chondroitin sulfate degradation i (bacterial) double,
  3,6-anhydro-alpha-l-galactopyranose degradation double,
  formaldehyde oxidation i double,
  s-adenosyl-l-methionine salvage i double,
  nitrate reduction viiib (dissimilatory) double,
  gamma-resorcylate degradation i double,
  anthranilate degradation i (aerobic) double,
  cdp-d-arabitol biosynthesis double,
  homocysteine and cysteine interconversion double,
  pyrimidine deoxyribonucleotides de novo biosynthesis iii double,
  s-methyl-5'-thioadenosine degradation i double,
  sulfate activation for sulfonation double,
  diphenyl ethers degradation double,
  5'-deoxyadenosine degradation ii double,
  polyhydroxydecanoate biosynthesis double,
  adenine and adenosine salvage vi double,
  glycine betaine degradation iii double,
  l-alanine biosynthesis ii double,
  l-arginine degradation xiii (reductive stickland reaction) double,
  adenine salvage double,
  group e salmonella o antigen biosynthesis double,
  lipoate biosynthesis and incorporation ii double,
  gdp-mannose biosynthesis double,
  formate to dimethyl sulfoxide electron transfer double,
  aerobic respiration ii (cytochrome c) (yeast) double,
  l-alanine biosynthesis iii double,
  alginate biosynthesis ii (bacterial) double,
  bacillithiol biosynthesis double,
  2-heptyl-3-hydroxy-4(1h)-quinolone biosynthesis double,
  formaldehyde assimilation ii (assimilatory rump cycle) double,
  5,5'-dehydrodivanillate degradation double,
  l-glutamate biosynthesis ii double,
  acyl-coa hydrolysis double,
  udp-n,n'-diacetylbacillosamine biosynthesis double,
  adenosylcobinamide-gdp salvage from cobinamide ii double,
  chitobiose degradation double,
  pyocyanin biosynthesis double,
  sulfoacetaldehyde degradation i double,
  l-arabinose degradation i double,
  phenylethanol biosynthesis double,
  cmp-3-deoxy-d-manno-octulosonate biosynthesis double,
  (aminomethyl)phosphonate degradation double,
  tca cycle viii (chlamydia) double,
  pseudouridine degradation double,
  cytosolic nadph production (yeast) double,
  dimethylsulfoniopropanoate degradation i (cleavage) double,
  oleate biosynthesis iv (anaerobic) double,
  pyruvate fermentation to butanoate double,
  superoxide radicals degradation double,
  l-valine degradation ii double,
  gentisate degradation i double,
  tetradecanoate biosynthesis (mitochondria) double,
  citronellol degradation double,
  nitrate reduction x (dissimilatory, periplasmic) double,
  nad salvage pathway iii (to nicotinamide riboside) double,
  hydrogen to dimethyl sulfoxide electron transfer double,
  nitrate reduction v (assimilatory) double,
  flexixanthin biosynthesis double,
  pyrimidine deoxyribonucleotides dephosphorylation double,
  l-glutamine degradation i double,
  l-lysine biosynthesis vi double,
  3,4,6-trichlorocatechol degradation double,
  sulfur oxidation i (aerobic) double,
  ubiquinol-9 biosynthesis (prokaryotic) double,
  anhydromuropeptides recycling i double,
  terminal olefins biosynthesis ii double,
  ump biosynthesis ii double,
  nitric oxide biosynthesis iii (bacteria) double,
  purine ribonucleosides degradation double,
  dimethyl sulfide degradation ii (oxidation) double,
  pyrrolnitrin biosynthesis double,
  2-oxoglutarate decarboxylation to succinyl-coa double,
  molybdenum cofactor biosynthesis double,
  l-cysteine degradation ii double,
  mannosylglucosylglycerate biosynthesis i double,
  l-proline degradation double,
  cytidylyl molybdenum cofactor biosynthesis double,
  glucosylglycerate biosynthesis ii double,
  oleate beta-oxidation double,
  4-hydroxy-2(1h)-quinolone biosynthesis double,
  l-tryptophan degradation i (via anthranilate) double,
  pyrroloquinoline quinone biosynthesis double,
  d-galactose degradation i (leloir pathway) double,
  phosphonoacetate degradation double,
  fatty acid beta-oxidation i (generic) double,
  vanillin and vanillate degradation ii double,
  s-methyl-5'-thioadenosine degradation iii double,
  flavin biosynthesis i (bacteria and plants) double,
  hydrogen sulfide biosynthesis i double,
  6-methylpretetramide biosynthesis double,
  l-threonine biosynthesis double,
  (1,3)-beta-d-xylan degradation double,
  8-amino-7-oxononanoate biosynthesis i double,
  glutathione-peroxide redox reactions double,
  purine deoxyribonucleosides degradation i double,
  methylglyoxal degradation iii double,
  nickel cofactor biosynthesis double,
  d-threitol degradation double,
  acinetoferrin biosynthesis double,
  dtdp-n-acetylthomosamine biosynthesis double,
  n-acetylglucosamine degradation i double,
  beta-alanine biosynthesis iii double,
  cdp-diacylglycerol biosynthesis ii double,
  folate transformations iii (e. coli) double,
  hexaprenyl diphosphate biosynthesis double,
  pyruvate fermentation to (s)-lactate double,
  d-glucarate degradation ii double,
  ubiquinol-7 biosynthesis (early decarboxylation) double,
  4-chlorocatechol degradation double,
  cis-genanyl-coa degradation double,
  anguibactin biosynthesis double,
  myo-inositol degradation i double,
  sucrose degradation iii (sucrose invertase) double,
  tetracycline resistance double,
  methanol oxidation to formaldehyde iii double,
  protein s-nitrosylation and denitrosylation double,
  androstenedione degradation i (aerobic) double,
  d-serine degradation double,
  l-proline biosynthesis i (from l-glutamate) double,
  formaldehyde oxidation v (bacillithiol-dependent) double,
  4-aminobutanoate degradation iii double,
  tetrapyrrole biosynthesis i (from glutamate) double,
  biotin biosynthesis from 8-amino-7-oxononanoate i double,
  lipoate salvage i double,
  l-aspartate biosynthesis double,
  hydrogen to fumarate electron transfer double,
  di-trans,poly-cis-undecaprenyl phosphate biosynthesis double,
  phosphopantothenate biosynthesis i double,
  testosterone degradation (anaerobic) double,
  guanine and guanosine salvage i double,
  pyrimidine nucleobases salvage i double,
  urea cycle double,
  aerobic respiration i (cytochrome c) double,
  formate assimilation into 5,10-methylenetetrahydrofolate double,
  sulfolactate degradation iii double,
  benzoyl-coa degradation iii (anaerobic) double,
  ump biosynthesis i double,
  terephthalate degradation double,
  urea degradation i double,
  mevalonate degradation double,
  methylglyoxal degradation i double,
  base-degraded thiamine salvage double,
  methylerythritol phosphate pathway i double,
  shikimate degradation i double,
  l-valine biosynthesis double,
  2-oxoisovalerate decarboxylation to isobutanoyl-coa double,
  guanosine deoxyribonucleotides de novo biosynthesis ii double,
  palmitate biosynthesis ii (type ii fatty acid synthase) double,
  l-ornithine biosynthesis i double,
  2,3-dihydroxybenzoate biosynthesis double,
  spermine biosynthesis double,
  carbazole degradation double,
  icosapentaenoate biosynthesis iv (bacteria) double,
  phenylmercury acetate degradation double,
  pyruvate fermentation to acetone double,
  pyruvate decarboxylation to acetyl coa iii double,
  trehalose biosynthesis iv double,
  d-allose degradation double,
  l-arginine biosynthesis iii (via n-acetyl-l-citrulline) double,
  (kdo)2-lipid a biosynthesis (p. gingivalis) double,
  pyruvate fermentation to acetoin iii double,
  taurine degradation i double,
  l-lysine biosynthesis i double,
  ethylmalonyl-coa pathway double,
  glutathionylspermidine biosynthesis double,
  group d1 salmonella o antigen biosynthesis double,
  udp-n-acetyl-d-glucosamine biosynthesis i double,
  ethylene glycol degradation double,
  2,4-dichlorophenoxyacetate degradation double,
  vancomycin resistance i double,
  fatty acid beta-oxidation iii (unsaturated, odd number) double,
  tunicamycin biosynthesis double,
  tetrathionate reduction i (to thiosulfate) double,
  l-ascorbate degradation i (bacterial, anaerobic) double,
  arsenate detoxification i (mammalian) double,
  polyphosphate metabolism double,
  ubiquinol-7 biosynthesis (prokaryotic) double,
  fatty acid biosynthesis initiation (bacteria and plants) double,
  pentose phosphate pathway (non-oxidative branch) ii double,
  long-chain fatty acid activation double,
  polyhydroxybutanoate biosynthesis double,
  thiazole component of thiamine diphosphate biosynthesis iv double,
  menaquinol-9 biosynthesis double,
  putrescine biosynthesis iii double,
  glyphosate degradation iii double,
  atp biosynthesis double,
  nadh repair (eukaryotes) double,
  l-histidine degradation i double,
  s-methyl-5-thio-alpha-d-ribose 1-phosphate degradation ii double,
  benzoate degradation ii (aerobic and anaerobic) double,
  periplasmic disulfide bond formation double,
  queuosine biosynthesis i (de novo) double,
  sulfoquinovose degradation i double,
  beta-dihydromenaquinone-9 biosynthesis double,
  l-threonine degradation i double,
  [2fe-2s] iron-sulfur cluster biosynthesis double,
  adenine and adenosine salvage v double,
  xanthan biosynthesis double,
  l-glutamate degradation ii double,
  cellulose biosynthesis double,
  fructoselysine and psicoselysine degradation double,
  d-galactarate degradation ii double,
  palmitoleate biosynthesis i (from (5z)-dodec-5-enoate) double,
  phosphate acquisition double,
  pyruvate fermentation to ethanol ii double,
  bis(guanylyl tungstenpterin) cofactor biosynthesis double,
  gluconeogenesis i double,
  taurine degradation iv double,
  glycolate and glyoxylate degradation i double,
  l-asparagine biosynthesis iii (trna-dependent) double,
  glycine cleavage double,
  oxalate degradation ii double,
  limonene degradation i (d-limonene) double,
  resorcinol degradation double,
  heme degradation iv double,
  pyruvate fermentation to (r)-acetoin ii double,
  n-end rule pathway i (prokaryotic) double,
  trans, trans-farnesyl diphosphate biosynthesis double,
  adenosylcobalamin biosynthesis from adenosylcobinamide-gdp i double,
  nad salvage pathway i (pnc vi cycle) double,
  putrescine degradation v double,
  pyrimidine deoxyribonucleotides de novo biosynthesis ii double,
  l-asparagine biosynthesis ii double,
  benzene degradation double,
  kanosamine biosynthesis ii double,
  d-sorbitol degradation ii double,
  homospermidine biosynthesis ii double,
  trna processing double,
  acinetobactin biosynthesis double,
  linezolid resistance double,
  trehalose biosynthesis i double,
  udp-alpha-d-glucose biosynthesis double,
  octane oxidation double,
  d-xylose degradation i double,
  s-adenosyl-l-methionine cycle ii double,
  (5z)-dodecenoate biosynthesis ii double,
  1,3-beta-d-glucan biosynthesis double,
  ethene biosynthesis iii (microbes) double,
  lipoate biosynthesis and incorporation i double,
  nadph repair (prokaryotes) double,
  2-deoxy-d-glucose 6-phosphate degradation double,
  (r,r)-butanediol degradation double,
  ammonia assimilation cycle iii double,
  myo-inositol biosynthesis double,
  nad salvage pathway iv (from nicotinamide riboside) double,
  1,5-anhydrofructose degradation double,
  putrescine degradation ii double,
  adp-l-glycero-beta-d-manno-heptose biosynthesis double,
  l-phenylalanine degradation i (aerobic) double,
  heparin degradation double,
  methylerythritol phosphate pathway ii double,
  protein n-glycosylation (bacterial) double,
  sulfide oxidation ii (flavocytochrome c) double,
  3,8-divinyl-chlorophyllide a biosynthesis i (aerobic, light-dependent) double,
  oxalate degradation i double,
  l-ascorbate degradation ii (bacterial, aerobic) double,
  udp-n-acetyl-alpha-d-galactosaminuronate biosynthesis double,
  phosphatidylcholine biosynthesis vii double,
  queuosine biosynthesis ii (queuine salvage) double,
  testosterone and androsterone degradation to androstendione double,
  l-glutamate degradation ix (via 4-aminobutanoate) double,
  trimethylamine degradation double,
  zeaxanthin-beta-d-diglucoside biosynthesis double,
  cellulose and hemicellulose degradation (cellulolosome) double,
  d-fructuronate degradation double,
  kojibiose degradation double,
  thiamine diphosphate salvage iii double,
  ubiquinol-9 biosynthesis (early decarboxylation) double,
  gallate degradation ii double,
  formaldehyde oxidation vii (thf pathway) double,
  d-arabinose degradation ii double,
  pentose phosphate pathway (non-oxidative branch) double,
  spermidine biosynthesis i double,
  l-glutamate degradation vi (to pyruvate) double,
  tetrahydrofolate biosynthesis i double,
  d-mannose degradation i double,
  l-rhamnose degradation ii double,
  succinate to cytochrome bd oxidase electron transfer double,
  s-methyl-5'-thioadenosine degradation ii double,
  acyl carrier protein activation double,
  l-lysine fermentation to acetate and butanoate double,
  arachidonate biosynthesis ii (bacteria) double,
  ferulate degradation double,
  l-malate degradation ii double)
LOCATION 's3://mmrc-bacterial-pathway/staging/sam'
TBLPROPERTIES (
  'table_type'='iceberg',
  'write_compression'='zstd'
);